name: Flask-CICD-Pipeline

on:
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
    
  workflow_dispatch:
    inputs:
      python_version:
        description: The python version to run on the runner
        required: true
        default: '3.12.6'
        type: string

      build_docker_image:
        description: Boolean value to build docker image
        required: true
        default: false
        type: boolean

env:
  python_version: '3.12.6'

jobs:
  test-push-pr:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code on the main branch
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}
    
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Test Cases
      run: |
        pytest

  test-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code on the main branch
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Test Cases
      run: |
        pytest

  build-deploy-push-pr: 
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    needs: ['test-push-pr']
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: shashankpalla/flask-cicd-pipeline:latest

  build-deploy-workflow-dispatch: 
    if: ${{ github.event_name == 'workflow-dispatch' && inputs.build_docker_image }}
    needs: ['test-workflow-dispatch']
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: shashankpalla/flask-cicd-pipeline:latest
