name: Flask-CICD-Pipeline

on:
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main
    
  workflow_dispatch:
    inputs:
      python_version:
        description: The python version to run on the runner
        required: true
        default: '3.12.6'
        type: string

      build_docker_image:
        description: Boolean value to build docker image
        required: true
        default: true
        type: boolean
        

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code on the main branch
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Test Cases
      run: |
        pytest

  build-deploy:
    env:
      build_condition: ${{ inputs.build_docker_image }}
    if: ${{ env.build_condition }}
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: shashankpalla/flask-cicd-pipeline:latest
